export const FETCH_POIS = 'FETCH_POIS';

export const TOGGLE_SHOW_HIDE_POI = 'TOGGLE_SHOW_HIDE_POI';

export const DELETE_POI = 'DELETE_POI';

export const ADD_NEW_POI = 'ADD_NEW_POI';

export const UPDATE_LAT_LON_ONCLICK_OR_ONSEARCH = 'UPDATE_LAT_LON_ONCLICK_OR_ONSEARCH';

export const CHANGE_POI_INFO = 'CHANGE_POI_INFO';

export const CHANGE_AMENITY = 'CHANGE_AMENITY';

export const SELECT_POI_FOR_EDIT = 'SELECT_POI_FOR_EDIT';

export const CLEAR_NEW_POI_INFO_STATE = 'CLEAR_NEW_POI_INFO_STATE';

export const UPDATE_POI_IN_STATE = 'UPDATE_POI_IN_STATE';

export const STORE_FETCHED_NODES_FROM_OVERPASS = 'STORE_FETCHED_NODES_FROM_OVERPASS';

export const CLEAR_FETCHED_NODES_FROM_OVERPASS = 'CLEAR_FETCHED_NODES_FROM_OVERPASS';

export const DISPLAY_FETCHED_NODES_XML_FROM_OSM = 'DISPLAY_FETCHED_NODES_XML_FROM_OSM';

export const EDIT_XML = 'EDIT_XML';

export const FETCH_NODES = 'FETCH_NODES';

export const CLEAR_XML_FOR_EDIT = 'CLEAR_XML_FOR_EDIT';
